<?php if (!defined('BASEPATH')) exit('No direct script access allowed');
class Profil_model extends CI_Model{ 
    public function __construct(){
        parent::__construct();
    }

 // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
		$this->db->or_like('keterangan', $q);
		$this->db->or_like('isi', $q);
		$this->db->from('profil');
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by("id", "ASC");
        $this->db->like('id', $q);
		$this->db->or_like('keterangan', $q);
		$this->db->or_like('isi', $q);
		$this->db->limit($limit, $start);
        return $this->db->get('profil')->result();
    }
    // get all
    public function get_all(){
        return $this->db->get('profil');
    }
    // get data by id
    public function get_by_id($id){
        $this->db->where('id', $id);
        return $this->db->get('profil')->row();
    }
    public function insert($data){
        if($this->db->insert('profil', $data)){
            $this->session->set_flashdata('success','<strong>Insert Successful.</strong> Profil insert successfully..!');
            return TRUE;
        }
        $this->session->set_flashdata('error','<strong>Insert Unsuccessful.</strong> Profil insert Unsuccessful..!');
        return FALSE;
    }
    public function update($data){
        $where['id'] = $this->input->post('id', TRUE);
        $this->db->update('profil', $data, $where);
        if($this->db->affected_rows() == 0){
            $this->session->set_flashdata('error','<strong>Update Unsuccessful.</strong> Profil update Unsuccessful..!');
            return FALSE;
        }
        $this->session->set_flashdata('success','<strong>Update Successful.</strong> Profil update successfully..!');
        return TRUE;
    }
    public function delete(){
        $id = $this->input->post('id',true);
        $success = array();
        $failed = array();
        foreach($id as $ids){
            $where['id'] = $ids;
            $this->db->delete('profil',$where);
            if($this->db->affected_rows() > 0){
                $success[] = 'berhasil';
            }else{
                $failed[] = $this->db->error();
            }
        }
        $jum_success = count($success);
        $jum_failed = count($failed);
        if(count($success) > 0){
            $status['type'] = 'success';
            $status['text'] = '<strong>Deleted..!</strong>Berhasil dihapus '.$jum_success.', Gagal dihapus '.$jum_failed.'..!!!';
            $status['title'] = 'Success';
        }else{
            $status['type'] = 'error';
            $status['text'] = '<strong>Oh snap!</strong> Proses hapus data gagal. '.$failed[0].'.';
            $status['title'] = 'Error';
        }
        echo json_encode($status);
    }
}

/* End of file Profil_model.php */
/* Location: ./application/models/Profil_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-01-06 23:18:10 */
/* http://harviacode.com */