<?php if (!defined('BASEPATH')) exit('No direct script access allowed');

class Profil extends CI_Controller{
    function __construct(){
        parent::__construct();
        $this->load->model('Profil_model');
    }

    public function index(){
        if (!$this->ion_auth->logged_in()){
            redirect('auth', 'refresh');
        }
        $q = urldecode($this->input->get('q', TRUE));
        $start = intval($this->input->get('start'));

        if ($q <> '') {
            $config['base_url'] = base_url() . 'profil/index.html?q=' . urlencode($q);
            $config['first_url'] = base_url() . 'profil/index.html?q=' . urlencode($q);
        } else {
            $config['base_url'] = base_url() . 'profil/index.html';
            $config['first_url'] = base_url() . 'profil/index.html';
        }

        $config['per_page'] = 10;
        $config['page_query_string'] = TRUE;
        $config['total_rows'] = $this->Profil_model->total_rows($q);

        $this->load->library('pagination');
        $this->pagination->initialize($config);

        $data = array(
            'profil_data' => $this->Profil_model->get_limit_data($config['per_page'], $start, $q),
            'q' => $q,
            'pagination' => $this->pagination->create_links(),
            'total_rows' => $config['total_rows'],
            'start' => $start,
            'url' => '',
            'profil' => 'active',
        );
        $this->load->view("admin/header",$data);
        $this->load->view("admin/profil/profil_list");
        $this->load->view("admin/footer");
    }
    public function read_profil($id){
        if (!$this->ion_auth->logged_in()){
            redirect('auth', 'refresh');
        }
        $data['get'] = $this->Profil_model->get_by_id($id);
        $isi['body'] = $this->load->view('admin/profil/profil_read',$data,true);
        $isi['modal_s'] = "";
        $isi['modal_footer'] = '<button type="button" class="btn btn-danger pull-right" data-dismiss="modal"><i class="fa fa-times"></i> Close</button>';
        $isi['modal_title'] = "Detail Profil";
        $this->load->view('modal',$isi);
    }
    public function create_profil(){
        if (!$this->ion_auth->logged_in()){
            redirect('auth', 'refresh');
        }
        $data["url"] = "";
        $data['action'] = "insert";
        $data["profil"] = "active";
        $this->load->view("header",$data);
        $this->load->view("admin/profil/profil_form");
        $this->load->view("footer");
    }
    public function update_profil($id){
        if (!$this->ion_auth->logged_in()){
            redirect('auth', 'refresh');
        }
        $data["url"] = "";
        $data['get'] = $this->Profil_model->get_by_id($id);
        $data['action'] = "update";
        $data["profil"] = "active";
        $this->load->view("admin/header",$data);
        $this->load->view("admin/profil/profil_form");
        $this->load->view("admin/footer");
    }
    public function save(){
        if (!$this->ion_auth->logged_in()){
            redirect('auth', 'refresh');
        }
        switch ($this->input->post('action',true)) {
        case 'insert':
            $data = array(
				'keterangan' => $this->input->post('keterangan',TRUE),
				'isi' => $this->input->post('isi',TRUE),
		    );
            $this->Profil_model->insert($data);
            redirect("Profil/create_profil");
            break;
        case 'update':
            $data = array(
				'keterangan' => $this->input->post('keterangan',TRUE),
				'isi' => $this->input->post('isi'),
		    );
            $this->Profil_model->update($data);
            redirect("profil/update_profil/".$this->input->post('id',TRUE));
            break;
        default:
            $this->Profil_model->delete();
            break;
        }       
    }
}

/* End of file Profil.php */
/* Location: ./application/controllers/Profil.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-01-06 23:18:10 */
/* http://harviacode.com */