<?php namespace App\Models;
use CodeIgniter\Model;
use SessionIdInterface;

class Pegawai_Model_Pns extends Model

{ 
    protected $table = 'pegawai_pns';
    protected $allowedFields = ['nama_pegawai','nip','jenis_kelamin','tempat_lahir','tgl_lahir','alamat','usia','cpns','pns','pangkat_gol','tmt_pangkat','tahun','bulan','berkala_awal','berkala_akhir','jenis_pegawai','agama','status_kawin','nama_pt','tingkat_pendidikan','program_studi','tahun_lulus','jabatan','eselon'];
    // datatables

    private function _get_datatables_query(){
        $column_order = array('pegawai_pns.nama_pegawai','pegawai_pns.nip','pegawai_pns.jenis_kelamin','pegawai_pns.tempat_lahir','pegawai_pns.tgl_lahir','pegawai_pns.alamat','pegawai_pns.usia','pegawai_pns.cpns','pegawai_pns.pns','pegawai_pns.pangkat_gol','pegawai_pns.tmt_pangkat','pegawai_pns.tahun','pegawai_pns.bulan','pegawai_pns.berkala_awal','pegawai_pns.berkala_akhir','pegawai_pns.jenis_pegawai','pegawai_pns.agama','pegawai_pns.status_kawin','pegawai_pns.nama_pt','pegawai_pns.tingkat_pendidikan','pegawai_pns.program_studi','pegawai_pns.tahun_lulus','pegawai_pns.jabatan','pegawai_pns.eselon',null);
        $column_search = array('pegawai_pns.nama_pegawai','pegawai_pns.nip','pegawai_pns.jenis_kelamin','pegawai_pns.tempat_lahir','pegawai_pns.tgl_lahir','pegawai_pns.alamat','pegawai_pns.usia','pegawai_pns.cpns','pegawai_pns.pns','pegawai_pns.pangkat_gol','pegawai_pns.tmt_pangkat','pegawai_pns.tahun','pegawai_pns.bulan','pegawai_pns.berkala_awal','pegawai_pns.berkala_akhir','pegawai_pns.jenis_pegawai','pegawai_pns.agama','pegawai_pns.status_kawin','pegawai_pns.nama_pt','pegawai_pns.tingkat_pendidikan','pegawai_pns.program_studi','pegawai_pns.tahun_lulus','pegawai_pns.jabatan','pegawai_pns.eselon');
        $orders = array('id' => 'asc');

        $this->db->table('pegawai_pns');
        //add this line for join
        //$this->db->join('table2', 'kcb_jekel.field = table2.field');
        //add this if join more two table
        //$this->db->join('table1', 'kcb_jekel.field = table1.field','inner'); 
        //$this->db->join('table2', 'kcb_jekel.field = table2.field','inner');
        $i = 0;
        foreach ($column_search as $item){
            if($_POST['search']['value']){
                if($i===0){
                    $this->groupStart();
                    $this->like($item, $_POST['search']['value']);
                }else{
                    $this->orLike($item, $_POST['search']['value']);
                }
                if(count($column_search) - 1 == $i) //last loop
                    $this->groupEnd();
            }
            $i++;
        }
        if(isset($_POST['order'])){
            $this->orderBy($column_order[$_POST['order']['0']['column']], $_POST['order']['0']['dir']);
        }else if(isset($orders)){
            $order = $orders;
            $this->orderBy(key($order), $order[key($order)]);
        }
    }
    public function get_datatables(){
        $this->_get_datatables_query();
        if($_POST['length'] != -1) $this->limit($_POST['length'], $_POST['start']);
        $query = $this->get();
        return $query->getResult();
    }
    public function count_filtered(){
        $this->_get_datatables_query();
        $query = $this->get();
        return $query->getNumRows();
    }
    public function count_all(){
        $this->table('pegawai_pns');
        return $this->countAllResults();
    }
    // get all
    public function get_all(){
        $this->db->table('pegawai_pns');
        return $this->get();
    }
    // get data by id
    public function get_by_id($id){
        $this->db->table('pegawai_pns');
        $this->where('id', $id);
        return $this->get()->getRow();
    }
    public function tambah($data){
        if($this->db->table('pegawai_pns')->insert($data)){
            return TRUE;
        }
        return $this->db->error();
    }
    public function ubah($id, $data){
        if($this->db->table('pegawai_pns')->update($data, array('id'=>$id))){
            return TRUE;
        }
        return $this->db->error();
    }
    public function hapus($id){
        $this->where('id',$id);
        if ($this->delete()){
            return TRUE;
        }
        return $this->db->error();
    }}
/* End of file Kcb_jekel_model.php */
/* Location: ./application/models/Kcb_jekel_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-10-29 08:24:44 */
/* http://harviacode.com */