<?php namespace App\Models;
use CodeIgniter\Model;
use SessionIdInterface;

class Register_model extends Model

{ 
    protected $table = 'register';
    protected $allowedFields = ['full_name','username','pasword','pasword2','email','email2'];
    // datatables
    private function _get_datatables_query(){
        $column_order = array('register.full_name','register.username','register.pasword','register.pasword2','register.email','register.email2',null);
        $column_search = array('register.full_name','register.username','register.pasword','register.pasword2','register.email','register.email2');
        $orders = array('id' => 'asc');

        $this->db->table('register');
        //add this line for join
        //$this->db->join('table2', 'kcb_jekel.field = table2.field');
        //add this if join more two table
        //$this->db->join('table1', 'kcb_jekel.field = table1.field','inner'); 
        //$this->db->join('table2', 'kcb_jekel.field = table2.field','inner');
        $i = 0;
        foreach ($column_search as $item){
            if($_POST['search']['value']){
                if($i===0){
                    $this->groupStart();
                    $this->like($item, $_POST['search']['value']);
                }else{
                    $this->orLike($item, $_POST['search']['value']);
                }
                if(count($column_search) - 1 == $i) //last loop
                    $this->groupEnd();
            }
            $i++;
        }
        if(isset($_POST['order'])){
            $this->orderBy($column_order[$_POST['order']['0']['column']], $_POST['order']['0']['dir']);
        }else if(isset($orders)){
            $order = $orders;
            $this->orderBy(key($order), $order[key($order)]);
        }
    }
    public function get_datatables(){
        $this->_get_datatables_query();
        if($_POST['length'] != -1) $this->limit($_POST['length'], $_POST['start']);
        $query = $this->get();
        return $query->getResult();
    }
    public function count_filtered(){
        $this->_get_datatables_query();
        $query = $this->get();
        return $query->getNumRows();
    }
    public function count_all(){
        $this->table('register');
        return $this->countAllResults();
    }
    // get all
    public function get_all(){
        $this->db->table('register');
        return $this->get();
    }
    // get data by id
    public function get_by_id($id){
        $this->db->table('register');
        $this->where('id', $id);
        return $this->get()->getRow();
    }
    public function tambah($data){
        if($this->db->table('register')->insert($data)){
            return TRUE;
        }
        return $this->db->error();
    }
    public function ubah($id, $data){
        if($this->db->table('register')->update($data, array('id'=>$id))){
            return TRUE;
        }
        return $this->db->error();
    }
    public function hapus($id){
        $this->where('id',$id);
        if ($this->delete()){
            return TRUE;
        }
        return $this->db->error();
    }}
/* End of file Kcb_jekel_model.php */
/* Location: ./application/models/Kcb_jekel_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-10-29 08:24:44 */
/* http://harviacode.com */